### ISSUE TITLE
[feature request] implement additional features

### ISSUE THREAD

**Issue by BachiMjavanadze** [robbycbennett/vscode-terminal-macros#5]
Please add icon on... somewhere to call `Terminal Macros` by one click. Add context menu command runner... not sure if you are interested at all so putting another extension's issues (author does not respond). If you are interested I can write detailly:

[https://github.com/easterapps/vscode-script-runner/issues](https://github.com/easterapps/vscode-script-runner/issues)

**Comment by RobbyCBennett** [comment]
I don't want to add that feature to my extension.

Additionally, I think that a specific [keyboard shortcut](https://github.com/RobbyCBennett/VSCodeTerminalMacros#execute-a-command-with-keyboard-shortcuts) can be faster than a context menu (2 clicks) or even something like a status bar icon (1 click).
